# Generated by Django 4.2.4 on 2023-08-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={},
        ),
    ]
