# Generated by Django 4.2.4 on 2023-08-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('garagem', '0003_veiculo_imagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='imagens',
            field=models.ManyToManyField(blank=True, default=None, related_name='+', to='uploader.image'),
        ),
    ]
