# Generated by Django 4.2.4 on 2023-08-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0005_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garagem.modelo'),
        ),
    ]
